### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by raphaelsander** [sibtc/simple-image-crop#3]
The example not open image after upload to crop.
Can you fix it?

**Comment by lavahasif** [comment]
https://github.com/lavahasif/simple-image-crop-master
use this example

**Comment by raphaelsander** [comment]
Hi @lavahasif 

Thanks for your answer.
I changed the idea, now I am using the side client crop to not use server resource to do it.
You can check more about in this [link](https://github.com/raphaelsander/SocialRep).
